plugins {
    id 'java'
    id 'application'
}

group = 'com.github.HarryPotato986'
version = '1.0-SNAPSHOT'

application {
    mainClass.set('com.github.HarryPotato986.Main')
}

repositories {
    mavenCentral()
}

dependencies {
    testImplementation platform('org.junit:junit-bom:5.10.0')
    testImplementation 'org.junit.jupiter:junit-jupiter'

    implementation 'com.github.librepdf:openpdf:3.0.0'
}

jar {
    manifest {
        attributes 'Main-Class' : 'com.github.HarryPotato986.Main'
    }

    from {
        configurations.runtimeClasspath.collect {it.isDirectory() ? it : zipTree(it)}
    }
}

test {
    useJUnitPlatform()
}